version: "3.1"

services:
  mongosrouter1:
    container_name: mongosrouter1
    build:
      context: .
      dockerfile: ./dockerfile
    networks:
      - mongoshard
    ports:
      - "29000:27017" 
    command: mongos --configdb "mongocfgs/mongocfgs:27017,mongocfgs1:27017,mongocfgs2:27017" --keyFile /etc/mongodb/key.keyFile   --port 27017  

  mongosrouter2:
    container_name: mongosrouter2
    build:
      context: .
      dockerfile: ./dockerfile
    networks:
      - mongoshard
    ports:
      - "29100:27017" 
    command: mongos --configdb "mongocfgs/mongocfgs:27017,mongocfgs1:27017,mongocfgs2:27017" --keyFile /etc/mongodb/key.keyFile   --port 27017  


networks:
  mongoshard:
    external: true
    name: mongoshardnet
