FROM mongo 

COPY ./key.keyFile /etc/mongodb/
COPY ./mongod.cfg /etc/mongod.conf

RUN chown 999 /etc/mongodb/key.keyFile
RUN chown 999 /etc/mongod.conf
RUN chmod 400 /etc/mongodb/key.keyFile
RUN chown 999 /data/*








