
FROM mongo 
COPY ./key.keyFile /etc/mongodb/

RUN chown 999 /etc/mongodb/key.keyFile
RUN chmod 400 /etc/mongodb/key.keyFile
RUN chown 999 /data/*

WORKDIR /srv/mongodb/rs0-0  
RUN chown mongodb:mongodb /srv/mongodb/rs0-0




RUN ls -a /etc/mongodb



